# Generated by Django 2.1.2 on 2018-10-26 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_expanded_user_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='/static/img/default_avatar.png', upload_to='avatars'),
        ),
    ]
