# Generated by Django 2.1.2 on 2018-10-26 01:20

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_fixed_default_avatar_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=django_countries.fields.CountryField(default='CA', max_length=2),
        ),
    ]
