# Generated by Django 2.1.2 on 2018-10-26 15:53

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_fixed_default_avatar_filepath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='/var/www/projectlovelace.net/lovelace-website/src/prod_static/img/default_avatar.png', upload_to=users.models.avatar_file_name),
        ),
    ]
