# Generated by Django 2.1.2 on 2018-10-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_fixed_default_avatar_filepath_v3'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='problems_solved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='submissions_made',
            field=models.IntegerField(default=0),
        ),
    ]
