# Generated by Django 2.1.2 on 2018-10-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_validators_and_help_text_for_user_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, help_text='Date format: YYYY-MM-DD.', null=True),
        ),
    ]
