# Generated by Django 2.1.2 on 2018-10-26 21:02

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_fixed_default_avatar_filepath_v4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='static/img/default_avatar.png', upload_to=users.models.avatar_file_name),
        ),
    ]
