# Generated by Django 2.1.5 on 2019-07-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_fixed_default_avatar_filepath_v5'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscribe_to_emails',
            field=models.BooleanField(default=True, help_text='Subscribe to emails.'),
        ),
    ]
