# Generated by Django 3.1.4 on 2020-12-26 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_subscribe_to_email_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
    ]
