# Generated by Django 2.0 on 2018-01-01 01:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('title', models.CharField(max_length=256)),
                ('date_added', models.DateField(default=datetime.date.today)),
                ('visible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('passed', models.BooleanField()),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='submission date')),
                ('language', models.CharField(max_length=256, verbose_name='programming language')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d', verbose_name='source code file')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='problems.Problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile')),
            ],
        ),
    ]
