# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 03:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('date_added', models.DateField(blank=True, default=datetime.date.today)),
                ('visible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date submitted')),
                ('language', models.CharField(max_length=64, verbose_name='programming language')),
                ('file', models.BinaryField(verbose_name='source code file')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='problems.Problem')),
            ],
        ),
    ]
