# Generated by Django 2.1.2 on 2018-10-20 00:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_auto_20181019_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='timesink',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)]),
        ),
    ]
