# Generated by Django 2.1.2 on 2018-10-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_problem_subjects_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='max_mem_usage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='submission',
            name='runtime_sum',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='submission',
            name='test_cases_passed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='test_cases_total',
            field=models.IntegerField(default=0),
        ),
    ]
