# Generated by Django 2.1.5 on 2019-07-31 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_nonunique-order-id'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='subfield',
            field=models.CharField(default='', max_length=64),
        ),
    ]
