# Generated by Django 3.1.6 on 2021-03-28 18:26

from django.db import migrations, models
import problems.models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0008_problem_subfields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(upload_to=problems.models.user_timestamped_filepath, verbose_name='source code file'),
        ),
    ]
